"""
Plot Tension from Simulation Data

This script plots the computed tension from simulation data.
It includes several plot types:

    1. Separate plots for 'no NP' and 'singles NP' data.
    2. A combined plot of both 'no NP' and 'singles NP'.
    3. Plots in both normal and logarithmic scales.
    4. Plots with error bars, based on bootstrap data if available.

The data is expected in a simple columnar format, generated by a bash
script. The columns are as follows:

    Name: Identifier of the data point (e.g., '0Oda', '5Oda').
    nr. Oda: Numerical value associated with the 'Name'.
    tension: Computed tension value.
    errorbar: Error value, if available (used for plotting error bars).

Notes:
    - The '0Oda' value is crucial as it represents the baseline for
        plotting differences.
    - The presence of an 'errorbar' value determines whether error bars
        are included in the plot.
Opt. by ChatGpt
Saeed
17 Jan 2023
"""


import typing
from dataclasses import dataclass, field

import pandas as pd
import matplotlib.pyplot as plt

from common import logger
from common import plot_tools
from common import my_tools
from common.colors_text import TextColor as bcolors


@dataclass
class BaseConfig:
    """
    Basic configurations and setup for the plots.
    """
    # pylint: disable=too-many-instance-attributes
    graph_suffix: str = 'tension.png'

    labels: dict[str, str] = field(default_factory=lambda: {
        'title': 'Computed Tension',
        'ylabel': r'$\Delta\gamma$',
        'xlabel': 'Nr. Oda'
    })

    graph_styles: dict[str, typing.Any] = field(default_factory=lambda: {
        'label': r'$\gamma$',
        'color': 'black',
        'marker': 'o',
        'linestyle': '--',
        'markersize': 5,
    })

    line_styles: list[str] = \
        field(default_factory=lambda: ['-', ':', '--', '-.'])
    colors: list[str] = \
        field(default_factory=lambda: ['black', 'red', 'blue', 'green'])

    height_ratio: float = (5 ** 0.5 - 1) * 2

    y_unit: str = r'[mN/nm$^2$]'

    log_x_axis: bool = False


@dataclass
class SimpleGraph(BaseConfig):
    """
    Parameters for simple data plots.
    """
    graph_suffix: str = 'converted_tension.png'


@dataclass
class RawGraph(BaseConfig):
    """
    Parameters for simple data plots.
    """
    graph_suffix: str = 'raw_tension.png'
    labels: dict[str, str] = field(default_factory=lambda: {
        'title': 'Computed Tension',
        'ylabel': r'$\gamma$',
        'xlabel': 'Nr. Oda'
    })
    y_unit: str = '[bar/nm]'


@dataclass
class LogGraph(BaseConfig):
    """
    Parameters for the semilog plots.
    """
    graph_suffix: str = 'log_xscale.png'
    labels: dict[str, str] = field(default_factory=lambda: {
        'title': 'Computed Tension',
        'ylabel': r'$\gamma$',
        'xlabel': 'log(Nr. Oda)'
    })
    log_x_axis: bool = True


@dataclass
class DoubleDataLog(LogGraph):
    """plot both data"""
    graph_suffix: str = 'log_xscale_both.png'
    graph_styles: dict[str, typing.Any] = field(default_factory=lambda: {
        'label': r'$\gamma$',
        'color': 'black',
        'marker': 'o',
        'linestyle': '--',
        'markersize': 5,
    })
    label_b: str = r'$\gamma_{np}$'


@dataclass
class ErrorBarGraph(BaseConfig):
    """
    Parameters for plots with error bars.
    """
    plot_errorbars: bool = True


@dataclass
class FileConfig:
    """
    Set the name of the input files for plot with labels say what are
    those
    """
    fnames: dict[str, str] = field(default_factory=lambda: {
        'no_np': 'tension.log',
        'with_np': 'tension_with_np.log'})


@dataclass
class ParameterConfig:
    """
    Parameters for the plots and conversions
    """
    tension_conversion: float = 20.0  # Convert bar/nm to mN/nm^2


@dataclass
class AllConfig(FileConfig, ParameterConfig):
    """
    Consolidates all configurations for different graph types.
    """
    simple_config: SimpleGraph = field(default_factory=SimpleGraph)
    raw_config: RawGraph = field(default_factory=RawGraph)
    log_config: LogGraph = field(default_factory=LogGraph)
    errbar_config: ErrorBarGraph = field(default_factory=ErrorBarGraph)
    double_config: DoubleDataLog = field(default_factory=DoubleDataLog)


class PlotTension:
    """
    Plot all the graphes
    """

    info_msg: str = 'Message from PlotTension:\n'
    configs: "AllConfig"

    def __init__(self,
                 log: logger.logging.Logger,
                 configs: "AllConfig" = AllConfig()
                 ) -> None:
        self.configs = configs
        tension_dict: dict[str, pd.DataFrame] = self._initiate_data(log)
        self.initiate_plots(tension_dict)
        self.write_msg(log)

    def _initiate_data(self,
                       log: logger.logging.Logger
                       ) -> pd.DataFrame:
        """read files and return the data in dataframes format"""
        tension_dict: dict[str, pd.DataFrame] = {}
        for key, fname in self.configs.fnames.items():
            my_tools.check_file_exist(fname, log)
            tension_dict[key] = self.read_file(fname)
        return tension_dict

    def read_file(self,
                  fname: str
                  ) -> pd.DataFrame:
        """read data file and return as a dataframe"""
        columns: list[str] = ['Name', 'nr.Oda', 'tension', 'errorbar']
        df_in: pd.DataFrame = \
            pd.read_csv(fname, delim_whitespace=True, names=columns)
        return df_in

    def initiate_plots(self,
                       tension_dict: dict[str, pd.DataFrame]
                       ) -> None:
        """plots the graphes"""
        nr_files: int = len(tension_dict)
        converted_dict: dict[str, pd.DataFrame] = {}
        for key, tension in tension_dict.items():
            self.plot_graph(key, tension, self.configs.raw_config)
            converted_tension: pd.DataFrame = self.convert_tension(tension)
            converted_dict[key] = converted_tension
            self.plot_graph(key,
                            converted_tension,
                            self.configs.simple_config,
                            col_name='converted_tension')
            self.plot_graph(key,
                            converted_tension,
                            self.configs.log_config,
                            col_name='converted_tension')
        if nr_files > 1:
            self.plot_all_tensions_log(converted_dict)

    def plot_all_tensions_log(self,
                              converted_dict: dict[str, pd.DataFrame]
                              ) -> None:
        """plot all the input in a same graph"""
        returned_fig = self.plot_graph('np_np',
                                       converted_dict['no_np'],
                                       self.configs.double_config,
                                       col_name='converted_tension',
                                       return_ax=True,
                                       add_key_to_title=False)
        if returned_fig:
            fig_i, ax_i = returned_fig

            ax_i.plot(converted_dict['with_np']['nr.Oda'],
                      converted_dict['with_np']['converted_tension'],
                      c=self.configs.double_config.colors[1],
                      ls=self.configs.double_config.graph_styles['linestyle'],
                      ms=self.configs.double_config.graph_styles['markersize'],
                      marker=self.configs.double_config.graph_styles['marker'],
                      label=self.configs.double_config.label_b
                      )
            plot_tools.save_close_fig(fig_i, ax_i, fname := 'double.png')
        self.info_msg += \
            f'\tThe raw tension plot for both data is saved as `{fname}`\n'

    def plot_graph(self,
                   key: str,
                   tension: pd.DataFrame,
                   configs: typing.Union[
                     SimpleGraph, RawGraph, LogGraph, DoubleDataLog],
                   col_name: str = 'tension',
                   return_ax: bool = False,
                   add_key_to_title: bool = True
                   ) -> typing.Union[tuple[plt.figure, plt.axis], None]:
        """plot the raw data for later conviniance"""
        # pylint: disable=too-many-arguments
        x_range: tuple[float, float] = (min(tension['nr.Oda']),
                                        max(tension['nr.Oda']))
        fig_i: plt.figure
        ax_i: plt.axes
        fig_i, ax_i = \
            plot_tools.mk_canvas(x_range, height_ratio=configs.height_ratio)
        if configs.log_x_axis:
            ax_i.set_xscale('log')
        ax_i.plot(tension['nr.Oda'], tension[col_name], **configs.graph_styles)

        ax_i.set_xlabel(configs.labels['xlabel'])
        ax_i.set_ylabel(f'{configs.labels["ylabel"]} {configs.y_unit}')
        if add_key_to_title:
            ax_i.set_title(f'{configs.labels["title"]} ({key})')
        else:
            ax_i.set_title(f'{configs.labels["title"]}')
        ax_i.grid(True, linestyle='--', color='gray', alpha=0.5)

        if return_ax:
            return fig_i, ax_i

        plot_tools.save_close_fig(
            fig_i, ax_i, fname := f'{key}_{configs.graph_suffix}')

        self.info_msg += \
            f'\tThe raw tension plot for `{key}` is saved as `{fname}`\n'

        return None

    def convert_tension(self,
                        tension: pd.DataFrame
                        ) -> pd.DataFrame:
        """convert the tension and subtract the amount at zero"""
        tension['converted_tension'] = \
            tension['tension'] - tension['tension'][0]
        tension['converted_tension'] /= self.configs.tension_conversion
        return tension

    def write_msg(self,
                  log: logger.logging.Logger  # To log
                  ) -> None:
        """write and log messages"""
        print(f'{bcolors.OKCYAN}{PlotTension.__name__}:\n'
              f'\t{self.info_msg}{bcolors.ENDC}')
        log.info(self.info_msg)


if __name__ == '__main__':
    PlotTension(log=logger.setup_logger('plot_tension.log'))
