# config/config.yaml
defaults:
  - files@files.rdf: rdf                   # Includes files/rdf.yaml
  - files@files.turn_points: turn_points   # Includes files/turn_points.yaml
  - files@files.contact: contact           # Includes files/contact.yaml
  - plots@plots.median: median             # Includes plots/median.yaml
  - plots@plots.turn_points: turn_points   # Includes plots/turn_points.yaml
  - plots@plots.contact_radii: contact_radii # Includes plots/contact_radii.yaml
  - plots@plots.contact_angles: contact_angles # Includes plots/contact_angles.yaml
