# config/config.yaml
defaults:
  - files@files.rdf: rdf                   # Includes files/rdf.yaml
  - files@files.turn_points: turn_points   # Includes files/turn_points.yaml
  - plots@plots.median: median             # Includes plots/median.yaml
  - plots@plots.turn_points: turn_points   # Includes plots/turn_points.yaml
