# conf/config.yaml
defaults:
  - inputs@inputs.residue_nr: residue_nr   # Includes inputs/residue_nr.yaml
  - inputs@inputs.atoms_per_residue: atoms_per_residue # Includes inputs/atoms_per_residue.yaml
  - inputs@inputs.box_info: box_info       # Includes inputs/box_info.yaml
  - inputs@inputs.tension_files: tension_files # Includes inputs/tension_files.yaml
  - inputs@inputs.molar_mass: molar_mass   # Includes inputs/molar_mass.yaml
  - inputs@inputs.langmuir_terms: langmuir_terms # Includes inputs/langmuir_terms.yaml
  - inputs@inputs.joeri: joeri             # Includes inputs/joeri.yaml
  - inputs@inputs.maas: maas               # Includes inputs/maas.yaml
experiment: 'maas'  # joeri (from yaml), or maas (from a xvg file)
log_x: True
log_y: False