"""
Plot GROMACS Data (RDF and CDF) from XVG Files

This script is intended for visualizing and analyzing data generated
by GROMACS, specifically focusing on the Radial Distribution Function
(RDF) and Cumulative Distribution Function (CDF) data contained within
xvg file formats. The script reads xvg files, extracts the relevant
data, and produces plots for easy interpretation and analysis of
molecular dynamics simulations.

Key Features:
- Supports parsing and plotting of RDF and CDF data from GROMACS xvg
    files.
- Customizable plotting options for clarity, presentation, and detailed
    analysis.
- Error handling for common issues encountered in xvg file parsing.
- Option to save plots in various formats for reporting and further
    use.

Usage:
The script requires xvg files generated by GROMACS as input. It extracts
the necessary data from these files and generates corresponding plots.
Users can customize plot attributes such as labels, colors, and line
styles. The resulting plots can be displayed on-screen or saved to a
file in formats like PNG, JPEG, or PDF.

Example:
    python plot_gromacs_data.py 

Note:
This script assumes a basic understanding of GROMACS output formats
and molecular dynamics simulation data.
It is designed to work with standard xvg file formats as generated by
GROMACS tools.

doc string by: ChatGpt
4 Jan, 2024
Saeed
"""
